env:
  global:
    - CC_TEST_REPORTER_ID=7538d0cb3dc638052737727cd2c092629f1f9dea02627a8843daf24938ab155d
language: node_js
node_js:
- '12'

dist: trusty

cache:
  directories:
    - "node_modules"
before_script:
  - psql -c "CREATE DATABASE address_book;" -U postgres
  - psql -c "CREATE USER emeka WITH PASSWORD 'password';" -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - "npm run nyc"

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false